server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: provider-service
          uri: lb://PROVIDER-SERVICE
          predicates:
            - Path=/providers/**
        - id: schedule-service
          uri: lb://SCHEDULE-SERVICE
          predicates:
            - Path=/slots/**
        - id: appointment-service
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/appointments/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/reviews/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: ThisIsAVeryStrongSecretKeyForJwtTokenGeneration123456